backend:
  name: git-gateway
  # name: 'test-repo'
display_url: https://strubelimutz.ch
# site_domain: cms.netlify.com
media_folder: 'site/static/img' # Folder where user uploaded files should go
public_folder: 'img'

collections: # A list of collections the CMS should be able to edit
  - name: 'pages'
    label: 'Seiten'
    files:
      - file: 'site/content/raumvermietung/_index.md'
        name: 'raumvermietung'
        label: 'Raumvermietung'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - { label: Inhalt, name: body, widget: markdown }
      - file: 'site/content/angebot/_index.md'
        name: 'angebot'
        label: 'Angebot'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - label: 'Werbetext'
            name: blurb
            widget: object
            fields:
              - { label: 'Titel', name: 'heading', widget: string }
              - { label: 'Text', name: 'text', widget: 'text' }
          - label: Angebote
            name: values
            widget: list
            fields:
              - { label: Titel, name: 'heading', widget: string }
              - { label: Text, name: 'text', widget: 'text' }
              - { label: Bild, name: imageUrl, widget: image }
              - { label: Link, name: 'buttonLink', widget: 'string' }
      - file: 'site/content/angebot/waldspielgruppe.md'
        name: 'waldspielgruppe'
        label: 'Angebot Waldspielgruppe'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - { label: Inhalt, name: body, widget: markdown }
      - file: 'site/content/angebot/innenspielgruppe.md'
        name: 'innenspielgruppe'
        label: 'Angebot Innenspielgruppe'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - { label: Inhalt, name: body, widget: markdown }
      - file: 'site/content/angebot/erlebnisnachmittag.md'
        name: 'erlebnisnachmittag'
        label: 'Angebot Erlebnisnachmittag'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - { label: Inhalt, name: body, widget: markdown }
      - file: 'site/content/_index.md'
        label: 'Home'
        name: 'home'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - {
              label: 'Aktuelles',
              name: news,
              widget: object,
              fields:
                [
                  { label: 'Sichtbar', name: 'displayed', widget: boolean },
                  { label: 'Titel', name: 'heading', widget: string },
                  { label: 'Text', name: 'text', widget: 'markdown' },
                ],
            }
          - {
              label: 'Unser Angebot',
              name: intro,
              widget: object,
              fields:
                [
                  { label: 'Titel', name: 'heading', widget: string },
                  { label: 'Text', name: 'text', widget: 'text' },
                ],
            }
          - {
              label: 'Unser Team',
              name: team,
              widget: object,
              fields:
                [
                  { label: 'Titel', name: 'heading', widget: string },
                  { label: 'Text', name: 'text', widget: 'text' },
                ],
            }
      - file: 'site/content/team/_index.md'
        name: 'team'
        label: 'Team'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - label: 'Werbetext'
            name: blurb
            widget: object
            fields:
              - { label: 'Titel', name: 'heading', widget: string }
              - { label: 'Text', name: 'text', widget: 'text' }
          - label: Portraits
            name: portraits
            widget: list
            fields:
              - { label: Titel, name: 'heading', widget: string }
              - { label: Text, name: 'text', widget: 'text' }
              - { label: Bild, name: imageUrl, widget: image }
              - label: Abschnitte
                name: sections
                widget: list
                fields:
                  - { label: Titel, name: heading, widget: string }
                  - { label: Einträge, name: list, widget: list }
      - file: 'site/content/about/_index.md'
        name: 'about'
        label: 'Über uns'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Bild, name: image, widget: image }
          - { label: Inhalt, name: body, widget: markdown }
      - file: 'site/content/contact/_index.md'
        name: 'contact'
        label: 'Kontakt'
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Untertitel, name: subtitle, widget: string }
          - { label: Bild, name: image, widget: image }
          - { label: E-Mail, name: email, widget: string }
          - { label: Inhalt, name: body, widget: markdown }
          - label: Kontakt Einträge
            name: contact_entries
            widget: list
            fields:
              - label: Titel
                name: heading
                widget: string
              - label: Text
                name: text
                widget: markdown
